# Generated by Django 4.1.3 on 2024-03-21 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0dd955b9-49c3-4293-a0db-231a407f2b52'), editable=False, primary_key=True, serialize=False)),
                ('configuration', models.TextField()),
                ('version_tag', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('diff', models.TextField(blank=True)),
                ('updated_config', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7729d7df-2eae-4c57-85af-1f8b89744890'), editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=22)),
                ('default_configuration_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_device', to='netconfapp.configuration')),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='netconfapp.device'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
