# Generated by Django 4.1.3 on 2024-03-23 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.UUIDField(default=uuid.UUID('56964802-7b2f-4150-b7e2-8d0da8a265e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4810e037-132a-4d13-b3ae-362294cde9b4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
