# Generated by Django 5.0.1 on 2024-03-20 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b07944bf-1cf1-43c9-918b-b28b8367c6ee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad7b7287-46d5-4b48-8fcd-56bcbc096ff3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
